name: Lint Code

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                    node-version: '20'

            - name: Configure npm to use the registry
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint